# -*- coding: utf-8 -*-
"""Copy of eclat.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lxIWDwbB61g6RuXrEcEJpYUBjQOkDeYU

# Eclat

## Importing the libraries
"""

!pip install apyori

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

"""## Data Preprocessing"""

# this model is simplify version of Apriori

dataset = pd.read_csv('Market_Basket_Optimisation.csv', header = None)

transactions = []
transactions_number = len(dataset)
transaction_item_number = dataset.shape[1]

for i in range (0, transactions_number):
  transactions.append([str(dataset.values[i,j]) for j in range(0, transaction_item_number)])

# printing test
#arr = np.array(transactions)
#newarr = arr.reshape(transactions_number, transaction_item_number)
#print(newarr)

"""## Training the Eclat model on the dataset"""

from apyori import apriori
rules = apriori(transactions = transactions, min_support = 0.003, min_confidence = 0.2, min_lift = 3, min_length = 2, max_length = 2)

"""## Visualising the results

### Displaying the first results coming directly from the output of the apriori function
"""

results = list(rules)

results

"""### Putting the results well organised into a Pandas DataFrame"""

def inspect(results):
    lhs         = [tuple(result[2][0][0])[0] for result in results]
    rhs         = [tuple(result[2][0][1])[0] for result in results]
    supports    = [result[1] for result in results]
    return list(zip(lhs, rhs, supports))
resultsinDataFrame = pd.DataFrame(inspect(results), columns = ['Product 1', 'Product 2', 'Support'])

"""### Displaying the results sorted by descending supports"""

resultsinDataFrame.nlargest(n = 10, columns = 'Support')