# -*- coding: utf-8 -*-
"""Copy of random_forest_regression.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CHWI2K0YFdAIrb5nU4NDJ9nXgrHAxAaw

# Random Forest Regression

## Importing the libraries
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

"""## Importing the dataset"""

dataset = pd.read_csv('Position_Salaries.csv')
X = dataset.iloc[:, 1:-1].values
y = dataset.iloc[:, -1].values

print('X:\n', X)
print('y:\n', y)
print('nulls num:\n', dataset.isnull().sum())

"""## Training the Random Forest Regression model on the whole dataset"""

from sklearn.ensemble import RandomForestRegressor

# n_estimators - number of trees, each tree is estimator
rnr = RandomForestRegressor(n_estimators=10, random_state=0)
rnr.fit(X,y)

"""## Predicting a new result"""

rnr.predict([[6.5]])

"""## Visualising the Random Forest Regression results (higher resolution)"""

# compare to Desiction tree regression here we have
# two sub levels between levels
X_grid = np.arange(min(X), max(X), 0.01)
X_grid = X_grid.reshape((len(X_grid), 1))
plt.scatter(X, y, color = 'red')
plt.plot(X_grid, rnr.predict(X_grid), color = 'blue')
plt.title('Truth or Bluff (Random Forest Regression)')
plt.xlabel('Position level')
plt.ylabel('Salary')
plt.show()