# -*- coding: utf-8 -*-
"""עותק של polynomial_regression.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1urClgCHjBybbanz3gPYcv6Hf-pacobnl

# Polynomial Regression

## Importing the libraries
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

"""## Importing the dataset"""

dataset = pd.read_csv('Data.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

#print('X:\n',X)
#print('y\n', y)

"""## Splitting the dataset into the Training set and Test set"""

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

"""## Training the Polynomial Regression model on the Training set"""

from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
pr = PolynomialFeatures(degree=4)
X_poly = pr.fit_transform(X_train)
#print(X_poly)
lr = LinearRegression()
lr.fit(X_poly, y_train)

"""## Predicting the Test set results"""

y_pred = lr.predict(pr.transform(X_test))
np.set_printoptions(precision=2)
y_pred_reshape = y_pred.reshape(len(y_pred),1)
y_test_reshape = y_test.reshape(len(y_test),1)
print(np.concatenate((y_pred_reshape,y_test_reshape),1))

"""## Evaluating the Model Performance"""

from sklearn.metrics import r2_score

print("R2 score: " + "{:.2f}".format(r2_score(y_test, y_pred)*100) + "%")